{% set name = "topoflow-d8-global-balance-csdms" %}
{% set version = "3.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms/topoflow-bridge

requirements:
  build:
    - bmi-babel
    - topoflow
  run:
    - bmi-babel
    - topoflow

test:
  requires:
    - pymt
    - bmi-tester

about:
  home: http://csdms.colorado.edu/wiki/Model_help:TopoFlow
  license: Apache
  summary: |
    The D8 algorithm is the most commonly used method for
    approximating flow directions on a topographic surface. This method
    tracks 'flow' from each point on a rectangular grid to one of its
    eight neighbors. The D8 method is well-suited for the identification
    of individual channels, channel networks, and basin boundaries.
    However, it does not fare as well for divergent flow over
    hillslopes. The TopoFlow D8Global component produces grids of flow
    codes, areas, channel widths, and channel lengths from an input
    digital elevation model (DEM).
